SAP/SAP/ViewModels/Orders/OrderItemViewModel.cs
using SAP.ViewModels.Catalogue;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SAP.ViewModels.Orders
{
    public class OrderItemViewModel
    {
        public Guid ItemId { get; set; }

        public ItemViewModel Item { get; set; }

        public int Quantity { get; set; }

        public decimal Price { get; set; }

        public AttributesViewModel Attributes { get; set; }
    }
}

SAP/SAP/ViewModels/Orders/OrderListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SAP.ViewModels.Orders
{
    public class OrderListViewModel
    {
        public List<OrderViewModel> Orders { get; set; }
    }
}

SAP/SAP/ViewModels/Orders/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SAP.ViewModels.Orders
{
    public class OrderViewModel
    {
        public Guid Id { get; set; }

        public DateTime CreateDate { get; set; }

        public ICollection<OrderItemViewModel> OrderItems { get; set; }

        public decimal TotalPrice { get; set; }

        public decimal DiscountCoef { get; set; }

        public decimal PriceWithDiscount { get; set; }
    }
}

SAP/SAP/Controllers/CatalogueController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SAP.Services;
using SAP.Services.Catalogue;

namespace SAP.Controllers
{
    [Route("catalogue")]
    public class CatalogueController : Controller
    {
        ICatalogueDataProvider CatalogueDataProvider { get; }

        ICartService CartService { get; }

        public CatalogueController(ICatalogueDataProvider catalogueDataProvider,
            ICartService cartService)
        {
            CatalogueDataProvider = catalogueDataProvider;
            CartService = cartService;
        }

        [Route("")]
        public async Task<ActionResult> Index()
        {
            var catalogue = await CatalogueDataProvider.GetCatalogueAsync();

            return View(catalogue);
        }

        [Route("node/{id}")]
        public async Task<ActionResult> Node(Guid id)
        {
            var catalogue = await CatalogueDataProvider.GetCatalogueAsync(id);
            return View("Index", catalogue);
        }

        [Route("item/{id}")]
        public async Task<ActionResult> Item(Guid id)
        {
            var item = await CatalogueDataProvider.GetItemAsync(id);
            item.IsInCart = await CartService.IsItemInCartAsync(id);
            return View(item);
        }
    }
}

SAP/SAP/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SAP.Services;

namespace SAP.Controllers
{
    [Authorize]
    [Route("orders")]
    public class OrdersController : Controller
    {
        IOrderService OrderService { get; }

        public OrdersController(IOrderService orderService)
        {
            OrderService = orderService;
        }

        [Route("")]
        public async Task<ActionResult> Index()
        {
            var orders = await OrderService.GetUserOrdersAsync();
            return View(orders);
        }

        [Route("details")]
        public async Task<ActionResult> Details(Guid id)
        {
            var order = await OrderService.GetOrderAsync(id);
            return View(order);
        }

        [Route("create")]
        public async Task<ActionResult> Create()
        {
            try
            {
                await OrderService.CreateOrderFromCartAsync();
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return View();
            }
        }

        [Route("cancel/{id}")]
        [HttpGet]
        public ActionResult Cancel(Guid id)
        {
            return View();
        }

        [Route("cancel")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SAP/SAP/Views/Orders/Details.cshtml
@model SAP.ViewModels.Orders.OrderViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Order details</h1>

<div>
    <h4>@Model.Id</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class="col-sm-10">
            @Model.CreateDate.ToString("dd.MM.yyyy")
        </dd>
        <dt class="col-sm-2">
            Total Price
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PriceWithDiscount)
        </dd>
    </dl>
    <div class="row">
        <div class="col">
            @foreach (var item in Model.OrderItems)
            {
                <div class="row">
                    <div class="col-3">
                        <img src="@item.Item.PictureUrl" />
                    </div>
                    <div class="col-9">
                        <dl class="row">
                            <dt class="col-3">
                                Name
                            </dt>
                            <dd class="col-9">
                                @item.Item.Name
                            </dd>
                        </dl>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to Orders list</a>
</div>

SAP/SAP/Views/Orders/Index.cshtml
@model SAP.ViewModels.Orders.OrderListViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model?.Orders?.Any() == true)
{
    <h1>Your orders</h1>

    <div>
        <div class="row">
            <div class="col-1">#</div>
            <div class="col-5">Order identifier</div>
            <div class="col-3">Creating date</div>
            <div class="col-3">Total price</div>
        </div>
        @{
            int i = 1;
            foreach (var order in Model.Orders)
            {
                <a class="text-dark" asp-controller="Orders" asp-action="Details" asp-route-id="@order.Id">
                    <div class="row">
                        <div class="col-1">@i</div>
                        <div class="col-5">@order.Id</div>
                        <div class="col-3">@order.CreateDate.ToString("dd.MM.yyyy")</div>
                        <div class="col-3">Total: @($"{order.TotalPrice}$")</div>
                    </div>
                </a>
                i++;
            }
        }
    </div>
}
else
{
    <h1>You have no orders yet</h1>
    <div>
        <a asp-controller="Catalogue" asp-action="Index">To Catalogue</a>
    </div>
}