SAP/SAP/ViewModels/Catalogue/Admin/CreateCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SAP.ViewModels.Catalogue.Admin
{
    public class CreateCategoryViewModel
    {
        public Guid? ParentId { get; set; }

        [Required]
        public string Name { get; set; }
    }
}

SAP/SAP/ViewModels/Catalogue/Admin/CreateItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace SAP.ViewModels.Catalogue.Admin
{
    [DataContract]
    public class CreateItemViewModel
    {
        [DataMember]
        [Required]
        public Guid CategoryId { get; set; }

        [DataMember]
        [Required]
        public string Name { get; set; }

        [DataMember]
        [MaxLength(50)]
        [Required]
        public string ManufacturerId { get; set; }

        [DataMember]
        public int QuantityInStock { get; set; }

        [DataMember]
        [Required]
        [MaxLength(2000)]
        public string PictureUrl { get; set; }

        [DataMember]
        public List<AttributesViewModel> Attributes { get; set; }
    }
}

SAP/SAP/ViewModels/Catalogue/ItemViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Threading.Tasks;

namespace SAP.ViewModels.Catalogue
{
    public class ItemViewModel : NodeViewModel
    {
        public Guid CategoryId { get; set; }

        public CategoryViewModel Category { get; set; }

        public string ManufacturerId { get; set; }

        public int QuantityInStock { get; set; }

        public bool IsInStock => QuantityInStock > 0;

        public string PictureUrl { get; set; }

        public List<AttributesViewModel> Attributes { get; set; }

        public SelectList AttributesToSelect { get; set; }

        public bool IsInCart { get; set; }
    }
}

SAP/SAP/Controllers/Admin/CatalogueAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SAP.Services.Catalogue;
using SAP.ViewModels.Catalogue;
using SAP.ViewModels.Catalogue.Admin;

namespace SAP.Controllers.Admin
{
    [Authorize]
    [Route("admin/catalogue")]
    public class CatalogueAdminController : Controller
    {
        private ICatalogueAdministration CatalogueAdministration { get; }

        private ICatalogueDataProvider CatalogueDataProvider { get; }

        public CatalogueAdminController(ICatalogueAdministration catalogueAdministration,
            ICatalogueDataProvider catalogueDataProvider)
        {
            CatalogueAdministration = catalogueAdministration;
            CatalogueDataProvider = catalogueDataProvider;
        }

        [Route("")]
        public async Task<ActionResult> Index()
        {
            var catalogue = await CatalogueDataProvider.GetCatalogueAsync();
            return View(catalogue);
        }

        [Route("node/{id}")]
        public async Task<ActionResult> Node(Guid id)
        {
            var catalogue = await CatalogueDataProvider.GetCatalogueAsync(id);
            return View("Index", catalogue);
        }

        [Route("create_category")]
        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        [Route("create_category")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateCategory(CreateCategoryViewModel category)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View();
                }

                await CatalogueAdministration.CreateCategoryAsync(category);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return View();
            }
        }

        [Route("create_item")]
        public ActionResult CreateItem()
        {
            return View();
        }

        [HttpPost]
        [Route("create_item")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateItem(CreateItemViewModel item)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }

                await CatalogueAdministration.CreateItemAsync(item);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return View();
            }
        }

        // Never implement delete of something by GET request!
        [Route("delete_item/{id}")]
        public async Task<ActionResult> Delete(Guid id)
        {
            await CatalogueAdministration.DeleteItemAsync(id);
            return RedirectToAction("Index");
        }
    }
}

SAP/SAP/Controllers/CatalogueController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SAP.Services;
using SAP.Services.Catalogue;

namespace SAP.Controllers
{
    [Route("catalogue")]
    public class CatalogueController : Controller
    {
        ICatalogueDataProvider CatalogueDataProvider { get; }

        ICartService CartService { get; }

        public CatalogueController(ICatalogueDataProvider catalogueDataProvider,
            ICartService cartService)
        {
            CatalogueDataProvider = catalogueDataProvider;
            CartService = cartService;
        }

        [Route("")]
        public async Task<ActionResult> Index()
        {
            var catalogue = await CatalogueDataProvider.GetCatalogueAsync();

            return View(catalogue);
        }

        [Route("node/{id}")]
        public async Task<ActionResult> Node(Guid id)
        {
            var catalogue = await CatalogueDataProvider.GetCatalogueAsync(id);
            return View("Index", catalogue);
        }

        [Route("item/{id}")]
        public async Task<ActionResult> Item(Guid id)
        {
            var item = await CatalogueDataProvider.GetItemAsync(id);
            item.IsInCart = await CartService.IsItemInCartAsync(id);
            return View(item);
        }
    }
}

SAP/SAP/Views/CatalogueAdmin/CatalogueNode.cshtml
@model IEnumerable<SAP.ViewModels.Catalogue.CategoryViewModel>

@if (Model != null)
{
    <ul>
        @foreach (var node in Model)
        {
            <li>
                <a class="nav-link text-dark" asp-area="" asp-controller="CatalogueAdmin" asp-action="Node" asp-route-id="@node.Id">@node.Name</a>
                @(await Html.PartialAsync("CatalogueNode", node.Childs))
            </li>
        }
    </ul>
}

SAP/SAP/Views/CatalogueAdmin/CreateCategory.cshtml
@model SAP.ViewModels.Catalogue.Admin.CreateCategoryViewModel

@{
    ViewData["Title"] = "CreateCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateCategory</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCategory">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ParentId" class="control-label"></label>
                <input asp-for="ParentId" class="form-control" />
                <span asp-validation-for="ParentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SAP/SAP/Views/CatalogueAdmin/CreateItem.cshtml
@model SAP.ViewModels.Catalogue.Admin.CreateItemViewModel

@{
    ViewData["Title"] = "CreateItem";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>CreateItem</h1>

<h4>CreateItemViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateItem">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturerId" class="control-label"></label>
                <input asp-for="ManufacturerId" class="form-control" />
                <span asp-validation-for="ManufacturerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="QuantityInStock" class="control-label"></label>
                <input asp-for="QuantityInStock" class="form-control" />
                <span asp-validation-for="QuantityInStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PictureUrl" class="control-label"></label>
                <input asp-for="PictureUrl" class="form-control" />
                <span asp-validation-for="PictureUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SAP/SAP/Views/CatalogueAdmin/Index.cshtml
@model SAP.ViewModels.Catalogue.CatalogueViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model?.RootCategories?.Any() == true)
{
    <div class="text-center">
        <h1>Catalogue administration</h1>
    </div>

    <div class="row">
        <div class="col-3">
            <div class="row text-center">
                <h3>Categories</h3>
            </div>
            <div class="row">
                <ul>
                    @foreach (var node in Model.RootCategories)
                    {
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="CatalogueAdmin" asp-action="Node" asp-route-id="@node.Id">@node.Name</a>
                            @(await Html.PartialAsync("CatalogueNode", node.Childs))
                        </li>
                    }
                </ul>
            </div>
        </div>
        <div class="col-9">
            <div class="row text-center">
                <h3>Items</h3>
            </div>
            <div class="row">
                @(await Html.PartialAsync("Items", Model.RootCategories.FirstOrDefault(x => x.IsSelected)))
            </div>
        </div>
    </div>
}
else
{
    <h1>Catalogue is empty</h1>
}

SAP/SAP/Views/CatalogueAdmin/Items.cshtml
@model SAP.ViewModels.Catalogue.CategoryViewModel

@if (Model?.Items?.Any() == true)
{
    @foreach (var item in Model.Items)
    {
        <div class="col-4">
            <a asp-area="" asp-controller="Catalogue" asp-action="Item" asp-route-id="@item.Id">
                <div class="row">
                    <img class="pl-3 pr-3" src="@item.PictureUrl" />
                </div>
                <div class="row">
                    <div class="col">
                        @item.Name
                    </div>
                    <div class="col">
                        @if (item.IsInStock)
                        {
                            <span class="text-success">In stock</span>
                        }
                        else
                        {
                            <span class="text-danger">Not in stock</span>
                        }
                    </div>
                </div>
            </a>
        </div>
    }
}
else if (Model?.Childs?.Any() == true)
{
    @(await Html.PartialAsync("Items", Model.Childs.FirstOrDefault(x => x.IsSelected)))
}
else
{
    <div>Go through catalogue deeper</div>
}